<?php
function li_get_post_types()
{
    $return = array();

    // Get WordPress post types
    $args = array(
        'public' => true,
        '_builtin' => true
    );
    $post_types = get_post_types($args, 'names', 'and');

    // Remove Attachments
    unset( $post_types['attachment'] );

    // Return only simple value
    if( count($post_types) ) foreach( $post_types as $post_type ) $return[] = $post_type;

    return $return;
}

/**
 * @param string $key
 * @return string
 * @example: https://baconipsum.com/api/?type=all-meat-filler&paras=5
 */
function li_get_rand_content( $key = 'post_title' )
{
    // Array of Lorem ipsum
    $array = array(
        array(
            'post_title' => 'Rump strip steak sausage jowl landjaeger meatloaf',
            'post_excerpt' => 'Ham hock spare ribs burgdoggen, meatloaf doner pig shankle pork loin alcatra prosciutto capicola jerky leberkas.  Salami spare ribs shankle burgdoggen andouille kevin pig, meatloaf alcatra strip steak turkey sausage boudin.  Burgdoggen landjaeger ham hock pancetta.',
            'post_content' => 'Bacon ipsum dolor amet salami boudin chuck jerky, picanha alcatra corned beef meatball biltong ham hock prosciutto drumstick burgdoggen t-bone tongue.  T-bone landjaeger prosciutto meatloaf sausage chicken short ribs tenderloin pig shank alcatra chuck.  Doner tail tongue rump pork belly ribeye short ribs.  Tenderloin pork chop beef ribs, strip steak capicola landjaeger andouille.  Meatball pig boudin bresaola.  Turducken turkey capicola strip steak.","Boudin tongue prosciutto, short loin venison ribeye ham corned beef.  Chicken pork belly picanha, andouille meatball shankle beef ribs rump pork.  Tail spare ribs turducken pork loin swine, ground round porchetta boudin short ribs flank tri-tip.  Pork loin meatball drumstick bresaola swine t-bone chicken pancetta cupim venison.","Ham pork chop ribeye shankle pork.  Swine capicola picanha burgdoggen cupim, jerky meatball drumstick venison.  Venison shankle sirloin pancetta pork chop kielbasa.  Tri-tip corned beef andouille pancetta ball tip turducken spare ribs boudin short ribs leberkas pork belly.","Tri-tip rump beef jowl ham hock pastrami swine doner ribeye tenderloin shoulder venison chuck beef ribs.  Ham hock spare ribs burgdoggen, meatloaf doner pig shankle pork loin alcatra prosciutto capicola jerky leberkas.  Salami spare ribs shankle burgdoggen andouille kevin pig, meatloaf alcatra strip steak turkey sausage boudin.  Burgdoggen landjaeger ham hock pancetta.  Rump strip steak sausage jowl landjaeger meatloaf salami tri-tip alcatra pastrami swine andouille brisket.  Leberkas ribeye boudin, picanha ball tip beef ribs pork chop flank ground round sirloin capicola turducken pork.  Meatball corned beef pancetta pork chop, bacon salami prosciutto bresaola pastrami ball tip short ribs.","Sausage pig shoulder turducken tail ball tip short loin t-bone burgdoggen jowl tenderloin biltong cow beef.  Short ribs boudin andouille salami.  Ball tip prosciutto meatball tenderloin burgdoggen filet mignon tail turducken turkey jowl ham hock.  Beef hamburger shankle bacon meatloaf cow porchetta.  Salami swine frankfurter tongue doner tenderloin pork chop pancetta bacon shank bresaola jowl shankle tail.'
        ),
        array(
            'post_title' => 'Capicola pork loin meatball, rump chicken alcatra chuck shankle ball tip drumstick cow',
            'post_excerpt' => 'Ribeye capicola chuck, t-bone cupim pork sirloin strip steak sausage pork belly cow short loin kevin.  Picanha porchetta ball tip meatball beef ribs boudin.  Venison shank pastrami pancetta.',
            'post_content' => 'Ham strip steak beef ribs, pork loin shankle bacon rump ball tip tri-tip meatball burgdoggen sausage kevin.  Boudin ham spare ribs andouille strip steak turkey.  Short ribs beef ribs capicola pork loin landjaeger flank pork belly pig cow venison chuck meatloaf tongue.  Meatloaf ribeye bresaola shankle turkey beef swine.  Short ribs sausage andouille shankle jerky alcatra ham hock beef ribs tri-tip kevin pork loin ball tip prosciutto chicken brisket.  Hamburger tenderloin landjaeger cupim sausage.  Pork chop turkey spare ribs, strip steak sirloin jerky beef ribs meatloaf t-bone picanha.","Ham hock fatback sirloin, tongue filet mignon swine rump.  Ribeye capicola chuck, t-bone cupim pork sirloin strip steak sausage pork belly cow short loin kevin.  Picanha porchetta ball tip meatball beef ribs boudin.  Venison shank pastrami pancetta.  Pork belly strip steak pork tongue sausage shank, tri-tip chicken corned beef landjaeger shankle turducken ground round ribeye cupim.  Flank brisket short loin chicken bacon pork belly strip steak rump pig, t-bone capicola cow swine drumstick.","Chuck swine capicola, andouille spare ribs bresaola ham leberkas landjaeger filet mignon pork belly pastrami fatback.  Jowl rump swine, doner pork loin short ribs meatloaf capicola venison.  Beef pastrami capicola ham prosciutto venison pork bacon, boudin spare ribs pork belly tenderloin pig.  Pork chop biltong tenderloin pork loin sausage pork belly shoulder kevin strip steak fatback.  Beef ribs burgdoggen short loin fatback beef ham, short ribs capicola pork loin andouille.  Capicola pork loin meatball, rump chicken alcatra chuck shankle ball tip drumstick cow.  Pork loin fatback chicken, cow shankle kielbasa kevin burgdoggen turkey porchetta ham beef.","Pastrami pork pork loin tri-tip, salami jowl ham kielbasa filet mignon.  Meatball ball tip jerky, capicola swine tongue chicken andouille.  Short ribs ribeye chuck spare ribs, bacon ground round turkey shoulder.  Drumstick tail meatball pork belly bresaola pancetta cow capicola fatback beef kevin biltong beef ribs.  Meatball pork loin boudin venison.  Doner tail jerky pork loin swine sausage short ribs.","Chuck ham flank kevin.  Ground round shankle doner beef jerky chicken frankfurter tongue pastrami pork loin ham hock.  Alcatra andouille tri-tip frankfurter landjaeger fatback.  Short loin burgdoggen picanha, drumstick turkey beef ribs ball tip shoulder alcatra chuck short ribs fatback cow pork belly corned beef.'
        ),
        array(
            'post_title' => 'T-bone flank pancetta salami filet mignon, drumstick pork chop tongue tri-tip',
            'post_excerpt' => 'Shank biltong jerky, meatball cupim chuck porchetta shankle pork kevin.  Pork pork belly jerky ribeye burgdoggen meatloaf corned beef.  Bresaola rump turducken pig cupim.  Leberkas filet mignon beef, strip steak turkey prosciutto biltong frankfurter bresaola.  Corned beef swine tail jowl burgdoggen ham hock rump.',
            'post_content' => 'Jerky swine sirloin meatball, shank cupim fatback rump frankfurter beef ribs.  Flank kielbasa frankfurter tenderloin.  Sausage pork salami shankle flank picanha.  Sirloin chuck pastrami spare ribs.  Alcatra chuck kielbasa ham andouille tenderloin swine ball tip sirloin.  Bresaola rump cupim flank ground round, short loin pig kevin.","Tri-tip cupim venison pork loin, jowl doner sirloin pork boudin cow beef frankfurter drumstick ham.  Capicola ground round t-bone swine pork corned beef shankle spare ribs.  Corned beef tri-tip short loin pancetta cupim bresaola porchetta, chuck ball tip brisket turkey.  Burgdoggen rump ham, frankfurter alcatra leberkas jowl.  Salami corned beef frankfurter, strip steak meatball ball tip doner pork belly ground round t-bone jowl hamburger boudin.  Venison sausage picanha, leberkas chicken fatback beef ribs shankle ham hock.","Rump pork belly tongue shank turducken fatback leberkas corned beef kielbasa short loin cupim filet mignon doner ground round boudin.  Strip steak shank chicken beef kevin, salami swine meatloaf rump.  Swine pork belly pork loin, meatloaf andouille tenderloin shankle short loin ground round kevin.  Pancetta drumstick ball tip t-bone biltong shoulder.  Turducken shankle pastrami, shoulder chuck frankfurter shank ball tip tri-tip.","T-bone flank pancetta salami filet mignon, drumstick pork chop tongue tri-tip.  Pork loin boudin t-bone brisket ground round, turkey chicken.  Ball tip biltong turducken swine cow, bacon corned beef salami filet mignon brisket alcatra.  Beef tongue burgdoggen cupim.  Fatback tenderloin bacon landjaeger.  Biltong capicola spare ribs landjaeger.  Prosciutto picanha salami shank beef ribs.","Landjaeger ham hock shank brisket, spare ribs pig andouille.  Salami chicken meatloaf kevin meatball tongue leberkas spare ribs sausage brisket shankle swine ribeye.  Shank biltong jerky, meatball cupim chuck porchetta shankle pork kevin.  Pork pork belly jerky ribeye burgdoggen meatloaf corned beef.  Bresaola rump turducken pig cupim.  Leberkas filet mignon beef, strip steak turkey prosciutto biltong frankfurter bresaola.  Corned beef swine tail jowl burgdoggen ham hock rump.'
        ),
        array(
            'post_title' => 'Porchetta capicola pork belly ribeye corned beef tail',
            'post_excerpt' => 'Pork belly ribeye corned beef tail. Ball tip meatloaf pork chop brisket, capicola swine rump ham hock kevin leberkas ground round hamburger.  Meatloaf biltong hamburger pancetta.  Tail jowl leberkas salami bresaola filet mignon shoulder rump beef ribs porchetta sirloin picanha kielbasa spare ribs pork.',
            'post_content' => 'Venison ribeye short ribs meatball prosciutto shank swine bresaola porchetta.  Beef picanha burgdoggen pig shank ribeye, drumstick t-bone prosciutto chicken short loin corned beef filet mignon shankle kevin.  Short ribs pork belly short loin ham salami, burgdoggen brisket chicken.  Biltong brisket landjaeger prosciutto chuck.","Jowl biltong picanha ham hock.  Spare ribs landjaeger biltong tail, tongue pancetta alcatra andouille rump tenderloin pork loin beef ribs pig bresaola fatback.  Tri-tip ball tip capicola brisket turkey.  Rump beef filet mignon pastrami pancetta venison.","Boudin pork meatball capicola flank pork loin, ham hock frankfurter andouille brisket ribeye.  Frankfurter hamburger doner, leberkas beef ribs chicken rump boudin flank filet mignon.  Corned beef tongue ball tip pig cow ham burgdoggen short ribs picanha.  Pork belly ham short loin, leberkas meatball hamburger jerky ham hock turducken drumstick picanha tenderloin.  Pig ground round flank shankle capicola cupim.  Porchetta capicola pork belly ribeye corned beef tail.","Ball tip meatloaf pork chop brisket, capicola swine rump ham hock kevin leberkas ground round hamburger.  Meatloaf biltong hamburger pancetta.  Tail jowl leberkas salami bresaola filet mignon shoulder rump beef ribs porchetta sirloin picanha kielbasa spare ribs pork.  Jerky ball tip fatback, ham hock landjaeger pancetta beef ribs doner chicken tongue spare ribs tri-tip.","Ball tip pork kielbasa t-bone tail rump.  Fatback burgdoggen pork chop salami chicken rump boudin andouille.  Brisket kevin alcatra ball tip swine hamburger.  Landjaeger tail ball tip cow kielbasa shank burgdoggen.  Porchetta filet mignon tongue flank ground round ribeye prosciutto, chicken biltong capicola corned beef sirloin hamburger turducken.'
        ),
        array(
            'post_title' => 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
            'post_excerpt' => 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.',
            'post_content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
        ),
        array(
            'post_title' => 'Shoulder shankle bresaola, porchetta pork chop spare ribs swine beef ribs cow tongue ground round shank',
            'post_excerpt' => 'Spare ribs pork loin beef ribs shank salami sausage pork leberkas, picanha ham hock jowl chicken capicola tongue short loin. Shoulder shankle bresaola, porchetta pork chop spare ribs swine beef ribs cow tongue ground round shank.  Ribeye fatback prosciutto ham hock.',
            'post_content' => 'Beef ribs bresaola kevin, flank kielbasa meatloaf pork.  Shank pork loin corned beef t-bone, meatball short ribs burgdoggen jowl rump pork ground round biltong frankfurter.  Kevin ground round drumstick corned beef, alcatra tri-tip pancetta tongue chuck venison burgdoggen pork loin pork chop leberkas.  Sirloin alcatra cow pork chop beef ball tip strip steak brisket.  Doner shoulder beef biltong alcatra boudin.","Corned beef jowl frankfurter filet mignon.  Beef ribs doner tongue t-bone, ball tip pork chop turkey landjaeger turducken rump andouille porchetta ground round bacon.  Spare ribs t-bone short loin andouille ham hock.  Pork belly andouille brisket sirloin picanha, pig frankfurter ball tip t-bone pork loin prosciutto tri-tip drumstick.  Corned beef short loin rump swine, hamburger turducken cow pork belly kevin pork chop salami venison pastrami meatball ribeye.  Capicola chuck jowl alcatra, doner flank picanha frankfurter pig burgdoggen.","Ball tip jerky pork tenderloin.  Venison kielbasa t-bone rump, kevin biltong ham shoulder brisket spare ribs.  Biltong bresaola meatball alcatra.  Short loin pork chop ham hock, flank shoulder bresaola beef ribs ribeye meatball porchetta filet mignon landjaeger salami fatback.  Shank frankfurter rump short loin burgdoggen ham.","Shoulder tenderloin biltong pastrami.  Salami cow biltong burgdoggen tail prosciutto.  Bacon chuck tongue cupim, landjaeger filet mignon shoulder drumstick tail ribeye salami beef.  Doner bresaola prosciutto alcatra short loin pork tenderloin tongue pig ribeye pork loin.  Doner beef pastrami kielbasa venison andouille swine flank chuck.  Salami turducken venison, kielbasa beef ribs pastrami meatball biltong sirloin t-bone pancetta brisket jowl.  Spare ribs pork loin beef ribs shank salami sausage pork leberkas, picanha ham hock jowl chicken capicola tongue short loin.","Shoulder shankle bresaola, porchetta pork chop spare ribs swine beef ribs cow tongue ground round shank.  Ribeye fatback prosciutto ham hock.  Meatloaf picanha sausage brisket pork belly short loin kielbasa rump boudin tongue doner tail flank.  Beef ham sirloin ground round leberkas, capicola brisket drumstick fatback salami boudin.  Jerky shoulder andouille, burgdoggen sirloin chicken turkey tri-tip filet mignon pork.'
        ),
        array(
            'post_title' => 'Ribeye jowl leberkas, pancetta swine turkey biltong short ribs',
            'post_excerpt' => 'Meatball tongue chuck, leberkas meatloaf picanha capicola.  Shank rump sirloin cupim ham hock porchetta pork chop ham cow biltong. Kevin turducken spare ribs boudin picanha biltong t-bone prosciutto turkey.',
            'post_content' => 'Meatball tri-tip shank picanha tenderloin spare ribs, jowl ribeye.  Short ribs drumstick burgdoggen turducken beef leberkas bresaola rump biltong turkey doner alcatra prosciutto sausage porchetta.  Filet mignon short loin ribeye cupim swine cow chuck.  T-bone doner ham hock jerky ground round strip steak.  Beef drumstick burgdoggen bacon pancetta pork loin strip steak filet mignon ham kielbasa sausage tri-tip bresaola t-bone.  Drumstick landjaeger picanha turkey swine pancetta andouille.","Pancetta pig alcatra burgdoggen tenderloin, ball tip bresaola turducken ribeye fatback venison strip steak pork loin.  Alcatra ham hock cow strip steak hamburger pastrami sirloin jowl shoulder t-bone rump spare ribs.  Tenderloin beef ribs sirloin, doner andouille salami sausage shankle fatback.  Ground round t-bone bresaola fatback jerky, meatloaf pork filet mignon.  Meatball tongue chuck, leberkas meatloaf picanha capicola.  Shank rump sirloin cupim ham hock porchetta pork chop ham cow biltong.","Kevin turducken spare ribs boudin picanha biltong t-bone prosciutto turkey.  Ball tip tenderloin shank bacon pork chop t-bone fatback swine beef corned beef capicola shoulder jerky.  Ham hock kevin jowl, cow tenderloin sirloin beef ribeye tri-tip beef ribs turkey.  Turkey strip steak boudin, bresaola leberkas jerky sirloin cupim beef corned beef.  T-bone pastrami pork belly spare ribs rump, tongue beef ribs venison chicken leberkas.  Ribeye jowl leberkas, pancetta swine turkey biltong short ribs frankfurter short loin.","Brisket pork ball tip ribeye cow boudin meatball landjaeger corned beef cupim.  Alcatra pork belly kielbasa biltong chuck.  Tri-tip flank boudin chuck drumstick cupim.  Jowl leberkas ribeye hamburger short loin t-bone.  Prosciutto short loin tail t-bone venison meatloaf alcatra, tenderloin hamburger pork belly bacon.","Cow brisket leberkas pork chop.  Sirloin turkey pork loin pork pork chop frankfurter shankle jowl fatback filet mignon rump doner tongue burgdoggen salami.  Turducken salami drumstick turkey pig cupim jowl kielbasa chicken.  Drumstick beef brisket tail pancetta tongue prosciutto pastrami venison andouille salami ham hock.  Cow flank pig shank, short loin frankfurter t-bone meatball tongue chicken porchetta ground round jowl.  Porchetta turkey pork loin boudin meatloaf cupim bacon, beef ribs filet mignon venison meatball hamburger.  Jowl pork chop tenderloin kevin prosciutto pork.'
        ),
        array(
            'post_title' => 'Kielbasa corned beef sausage, burgdoggen ham filet mignon porchetta doner',
            'post_excerpt' => 'Landjaeger jowl tenderloin shank pork belly kielbasa short ribs beef ham doner swine.","Turducken prosciutto ham hock kevin leberkas.  Porchetta shankle picanha landjaeger tongue sausage boudin leberkas beef ribs pig shank fatback ham hock cow.  Capicola picanha pork loin.',
            'post_content' => 'Venison pork ball tip bresaola, porchetta fatback jerky shank filet mignon spare ribs sirloin tenderloin rump boudin pancetta.  Alcatra rump capicola meatball.  T-bone porchetta chicken prosciutto turkey.  Salami tongue corned beef, tail prosciutto short loin flank capicola bresaola shank.  Landjaeger jowl tenderloin shank pork belly kielbasa short ribs beef ham doner swine.","Turducken prosciutto ham hock kevin leberkas.  Porchetta shankle picanha landjaeger tongue sausage boudin leberkas beef ribs pig shank fatback ham hock cow.  Capicola picanha pork loin, tail leberkas doner swine kevin beef chuck t-bone jowl biltong turkey.  Pork short loin tongue picanha pig.","Short loin shankle prosciutto, short ribs venison pork loin kielbasa beef ribs sirloin strip steak leberkas pig cupim boudin shoulder.  Pork belly burgdoggen doner, brisket boudin ham sirloin frankfurter.  Kielbasa corned beef sausage, burgdoggen ham filet mignon porchetta doner.  Bresaola strip steak swine pork chop pork belly chuck.  Chicken pastrami sirloin beef ribs doner short loin leberkas venison filet mignon jowl turducken meatball shank jerky.  Ham capicola porchetta biltong tenderloin short loin short ribs filet mignon rump cow chicken.","Cow prosciutto tongue brisket.  T-bone sausage alcatra sirloin tenderloin swine brisket prosciutto pork tri-tip meatball.  Kielbasa salami pork loin tail.  Pig rump alcatra biltong venison.  Doner tenderloin picanha short ribs flank alcatra hamburger pork chop frankfurter tail chuck ribeye burgdoggen rump.","Prosciutto meatloaf picanha porchetta boudin, bacon alcatra flank venison pork belly tail chuck pancetta leberkas shoulder.  Ground round shoulder bresaola pancetta.  Fatback tenderloin filet mignon pastrami pork biltong porchetta corned beef, tri-tip pork belly boudin shankle shank.  Beef ribs rump jerky hamburger.  Boudin turducken cow beef ribs capicola strip steak bresaola doner pork belly swine short ribs ground round jowl.  Venison bresaola t-bone ground round flank corned beef capicola turkey rump shoulder kielbasa.'
        ),
        array(
            'post_title' => 'Meatloaf strip steak frankfurter, porchetta short loin chicken tri-tip jowl meatball',
            'post_excerpt' => 'Chicken prosciutto jerky, shoulder beef ham kevin landjaeger doner tail short ribs pork swine cow meatloaf.  Cow pig doner kielbasa spare ribs.',
            'post_content' => 'Alcatra ham sirloin, beef sausage tongue corned beef pastrami cow.  Cow prosciutto swine, burgdoggen ribeye flank landjaeger boudin beef ribs.  Ground round rump jerky shankle tenderloin spare ribs, tongue short loin pancetta salami sausage t-bone burgdoggen jowl.  Cupim strip steak tongue tri-tip ball tip, pig chuck drumstick tail boudin frankfurter.  Ham hock hamburger pork ground round pork loin cow.  Ground round pork chop drumstick ribeye brisket.","Chicken prosciutto jerky, shoulder beef ham kevin landjaeger doner tail short ribs pork swine cow meatloaf.  Cow pig doner kielbasa spare ribs.  Andouille porchetta fatback, cupim filet mignon prosciutto rump short loin swine pig bacon pork strip steak drumstick boudin.  Jowl meatball swine, salami spare ribs pork belly cow cupim flank filet mignon.  Fatback alcatra sausage cupim spare ribs.  Pancetta filet mignon porchetta, meatloaf fatback meatball shankle andouille.","Tenderloin filet mignon burgdoggen t-bone, chuck flank andouille prosciutto hamburger venison cow pastrami ball tip salami pork belly.  Salami pork belly ham hock beef turkey.  Corned beef biltong fatback meatball cupim, pig chicken shankle filet mignon leberkas.  Picanha tenderloin beef, ribeye sausage andouille spare ribs cow short loin.  Ribeye capicola pastrami turducken venison.  Porchetta boudin tongue shankle brisket corned beef andouille cow short loin pancetta t-bone pork sausage.  Swine pork brisket, fatback short ribs frankfurter ribeye chuck.","Ground round jowl short ribs beef ribs.  Swine tail prosciutto beef ribs, capicola venison tenderloin beef drumstick tongue pork loin ribeye rump frankfurter.  Chuck tenderloin kevin, cow t-bone shankle ham ham hock turducken porchetta.  Tenderloin cupim shoulder, swine flank meatloaf chicken turducken ham.","Burgdoggen bresaola sausage landjaeger venison chuck pork cow pork loin picanha swine turducken chicken biltong.  Cupim ham hock ground round, pork loin jowl hamburger t-bone frankfurter pancetta landjaeger andouille beef tenderloin alcatra.  Tenderloin short ribs swine t-bone jerky strip steak.  Cow pancetta meatloaf burgdoggen.  Meatloaf strip steak frankfurter, porchetta short loin chicken tri-tip jowl meatball doner ham hock rump burgdoggen.  Tail andouille venison alcatra bacon, jowl pastrami sirloin strip steak shankle kevin shoulder spare ribs.  Burgdoggen beef ribs cow, andouille hamburger biltong fatback filet mignon pastrami sausage brisket pork loin cupim.'
        ),
        array(
            'post_title' => 'Tenderloin kielbasa filet mignon, meatball pig bresaola ribeye pork chop cupim cow brisket',
            'post_excerpt' => 'Andouille cupim sirloin tongue drumstick ribeye prosciutto turducken salami.  Salami beef meatball jowl, strip steak pig drumstick ham hock ribeye chicken alcatra. Burgdoggen alcatra salami sirloin swine t-bone beef capicola pork chop bacon pork loin ham kielbasa kevin.  Tri-tip pork loin venison brisket frankfurter.',
            'post_content' => 'Short ribs pancetta shankle andouille venison meatloaf rump tongue.  Pig shoulder salami biltong, landjaeger cupim hamburger boudin jerky.  Pork belly pork turducken jowl, salami pig hamburger turkey burgdoggen filet mignon kevin shoulder.  Chuck picanha ground round fatback, alcatra tail kevin pork turkey meatloaf ham hock pig drumstick jowl pork loin.  Chicken jowl pastrami, porchetta pig bresaola ball tip.  Tenderloin kielbasa filet mignon, meatball pig bresaola ribeye pork chop cupim cow brisket.  Picanha pork belly biltong turducken, sausage cupim chuck tongue pig rump pork chop prosciutto.","Kevin boudin cupim leberkas, beef ribs short loin venison fatback jerky filet mignon pork chop burgdoggen ribeye spare ribs.  Landjaeger cupim beef, tenderloin shankle fatback pork belly salami shank picanha meatball kielbasa turducken frankfurter.  Pastrami landjaeger tri-tip, andouille jowl fatback flank shank hamburger.  Chuck bacon sirloin sausage.  Cupim leberkas pork belly pig kevin.  Tail pork loin picanha, meatball kielbasa filet mignon rump beef chicken.","Short ribs andouille burgdoggen prosciutto doner shankle.  Doner tail short loin picanha meatball shoulder, beef shank bresaola turducken sirloin.  Ground round shank picanha sirloin beef pastrami porchetta cow ham hock corned beef, prosciutto hamburger.  Flank chuck prosciutto ground round, porchetta shoulder cupim beef ribs sausage drumstick kielbasa cow bresaola jerky.  Andouille cupim sirloin tongue drumstick ribeye prosciutto turducken salami.  Salami beef meatball jowl, strip steak pig drumstick ham hock ribeye chicken alcatra.","Burgdoggen alcatra salami sirloin swine t-bone beef capicola pork chop bacon pork loin ham kielbasa kevin.  Tri-tip pork loin venison brisket frankfurter.  Leberkas pork capicola spare ribs.  Flank bacon kielbasa short ribs.","Beef ribs shoulder beef bacon ham hock tongue t-bone pastrami frankfurter pork jerky bresaola turducken.  Andouille fatback turducken cupim burgdoggen pork belly turkey tail tongue.  Ground round jerky biltong cupim tongue fatback turkey pork hamburger meatloaf cow pig pastrami.  Biltong flank beef ribs strip steak chuck alcatra.  Biltong leberkas tenderloin flank, shank pork chop chicken.  Boudin sausage pork belly meatball leberkas, prosciutto tongue sirloin swine tail ham pork pork chop rump.  Bacon shoulder filet mignon, kevin sirloin swine rump ribeye turducken tongue pastrami ham kielbasa landjaeger frankfurter.'
        ),
        array(
            'post_title' => 'Meatball brisket pork filet mignon pancetta.  Ball tip short loin shoulder pig!',
            'post_excerpt' => 'Biltong tri-tip hamburger, jowl drumstick prosciutto pork bacon t-bone leberkas strip steak ham hock.  Strip steak bacon tri-tip leberkas jowl.  Meatball brisket pork filet mignon pancetta.  Ball tip short loin shoulder pig pork belly ribeye rump salami brisket tri-tip prosciutto landjaeger.","Ham hock chuck cow kevin boudin.',
            'post_content' => 'Pork chop ground round spare ribs cupim ham hock shankle sirloin hamburger.  Capicola jerky brisket fatback.  Ground round shank porchetta tongue, tail beef ribs picanha bacon.  Spare ribs turkey ham tenderloin landjaeger kevin bacon cow fatback biltong shank meatloaf.  Pork loin chicken burgdoggen landjaeger cow tail shoulder kevin, meatloaf short loin.","Tail jowl pork belly pancetta doner meatball beef ribs ribeye fatback corned beef drumstick cow prosciutto ham short loin.  Meatball cupim pastrami, strip steak pork biltong shank burgdoggen.  Rump capicola ham doner landjaeger ground round.  Ham pastrami short ribs, ham hock salami jerky doner corned beef pancetta chicken turducken sirloin drumstick venison prosciutto.  Shankle bacon ham burgdoggen, tenderloin alcatra pancetta spare ribs capicola boudin chicken pig fatback andouille.","Venison ball tip ground round turducken pork loin sirloin.  Prosciutto filet mignon porchetta tail ribeye chicken salami pancetta ham hock short loin cow.  Biltong tri-tip hamburger, jowl drumstick prosciutto pork bacon t-bone leberkas strip steak ham hock.  Strip steak bacon tri-tip leberkas jowl.  Meatball brisket pork filet mignon pancetta.  Ball tip short loin shoulder pig pork belly ribeye rump salami brisket tri-tip prosciutto landjaeger.","Ham hock chuck cow kevin boudin tri-tip bresaola capicola venison beef ribs sirloin frankfurter meatball ground round.  Shoulder drumstick pastrami porchetta capicola pancetta.  Burgdoggen doner tongue, meatball alcatra ground round t-bone capicola pork loin chicken salami filet mignon short ribs tenderloin.  Turducken shoulder corned beef brisket cupim tongue bresaola tail bacon meatball boudin picanha capicola.","Kielbasa pork loin meatloaf ham hock, chuck flank ground round corned beef fatback doner landjaeger filet mignon ball tip tenderloin.  Tail corned beef venison shank.  Porchetta ham cupim pork frankfurter fatback shankle, boudin pork chop alcatra salami ribeye flank cow.  Pastrami ribeye tongue shank turducken hamburger.'
        ),
        array(
            'post_title' => 'Turducken jowl alcatra ham cow andouille beef ribs kevin',
            'post_excerpt' => 'Flank andouille t-bone biltong kielbasa leberkas.  Tongue chuck fatback alcatra, ball tip chicken ground round short loin shank t-bone beef brisket corned beef kielbasa doner.","Doner sirloin t-bone pork chop.  Capicola pork loin brisket prosciutto, pancetta tri-tip ribeye sirloin.  Beef ribs cupim boudin.',
            'post_content' => 'Chuck hamburger venison short ribs drumstick prosciutto bresaola boudin kevin.  Ball tip shoulder ground round pork loin sirloin, spare ribs tail pork chop leberkas strip steak pancetta frankfurter.  Andouille beef ribs pancetta strip steak leberkas swine.  Turkey bacon kevin picanha pork chop flank meatball ham.  Pastrami hamburger short loin shankle corned beef pork shoulder bresaola frankfurter jowl chicken capicola pork loin.  Short loin spare ribs filet mignon leberkas salami bacon.  Turkey leberkas kevin pancetta picanha short loin.","Shank swine shankle bresaola filet mignon drumstick leberkas short loin venison meatloaf burgdoggen kielbasa pork alcatra beef ribs.  Pork belly alcatra prosciutto, turducken capicola bacon beef ribs burgdoggen brisket andouille picanha pig cupim.  Pork loin sausage meatloaf shoulder.  Cow kevin andouille meatball chuck flank landjaeger porchetta rump tongue shankle filet mignon pancetta leberkas.  Andouille shank alcatra, tongue beef ribs bacon flank brisket kevin pork shankle chuck frankfurter sausage.  Pancetta meatloaf turkey, ribeye salami frankfurter tongue sirloin.  Jowl biltong pork chop cow spare ribs frankfurter, tongue pastrami boudin rump shankle.","Pastrami tongue turducken biltong hamburger jowl burgdoggen meatball ground round.  Shoulder pork belly landjaeger, doner cupim boudin shank filet mignon.  Boudin salami picanha pancetta pig shoulder beef fatback strip steak.  Chuck pancetta kevin, prosciutto andouille brisket cow doner.  Frankfurter cow spare ribs pork belly shankle.  Turducken jowl alcatra ham cow andouille beef ribs kevin frankfurter biltong.","Tongue swine bacon pork loin, alcatra tenderloin corned beef pork chop doner boudin shankle tail fatback.  Pig tongue flank, short loin beef shank brisket.  Turkey bacon ground round, pork chop frankfurter alcatra kielbasa.  Frankfurter rump shoulder, turkey beef ribs kevin sirloin jerky doner shankle ham cupim kielbasa.  Andouille t-bone frankfurter landjaeger salami, tri-tip drumstick short loin tenderloin pastrami shank jerky leberkas.  Frankfurter ribeye pork chop spare ribs pork picanha tenderloin chuck flank andouille t-bone biltong kielbasa leberkas.  Tongue chuck fatback alcatra, ball tip chicken ground round short loin shank t-bone beef brisket corned beef kielbasa doner.","Doner sirloin t-bone pork chop.  Capicola pork loin brisket prosciutto, pancetta tri-tip ribeye sirloin.  Beef ribs cupim boudin frankfurter tongue pastrami salami alcatra.  Swine picanha ground round, sirloin leberkas prosciutto shank rump tail doner corned beef burgdoggen.  Chuck strip steak chicken, swine turducken short loin leberkas venison ball tip prosciutto hamburger pig rump.  Doner rump shank bresaola biltong turducken.  Ribeye pancetta corned beef, boudin shankle pork loin venison pork belly.'
        ),
        array(
            'post_title' => 'Meatball cupim tenderloin spare ribs picanha jowl',
            'post_excerpt' => 'Pork cow leberkas biltong tongue chicken.  Landjaeger prosciutto ball tip frankfurter ground round bresaola turkey cow sausage hamburger leberkas jowl meatloaf brisket.  Beef boudin bresaola filet mignon ribeye beef ribs.  Hamburger meatloaf spare ribs, shank cow ham kielbasa shoulder pork.',
            'post_content' => 'Sirloin rump meatball bresaola drumstick leberkas pastrami andouille turducken kielbasa shoulder chuck frankfurter.  Turducken filet mignon shank salami beef.  Pork leberkas ball tip salami turkey kielbasa, boudin drumstick kevin jowl tail capicola swine andouille.  Alcatra swine pork belly, chuck jerky andouille shankle t-bone kevin.","Brisket beef ribs shank pancetta.  Spare ribs hamburger pork loin chuck, pork belly prosciutto cupim fatback ham hock strip steak cow flank bresaola porchetta.  Spare ribs rump meatloaf t-bone doner, strip steak frankfurter shoulder ham hock pork belly ground round beef bacon jerky.  Meatball sausage venison t-bone tenderloin.  Flank chuck ham, turkey jerky rump beef tail.  Alcatra drumstick sausage corned beef.","Pork cow leberkas biltong tongue chicken.  Landjaeger prosciutto ball tip frankfurter ground round bresaola turkey cow sausage hamburger leberkas jowl meatloaf brisket.  Beef boudin bresaola filet mignon ribeye beef ribs.  Hamburger meatloaf spare ribs, shank cow ham kielbasa shoulder pork.  Short loin landjaeger cupim bresaola, shoulder pastrami porchetta pig spare ribs.  Kevin andouille drumstick, boudin hamburger ham salami meatloaf.  Bresaola flank alcatra meatloaf, shank porchetta biltong pastrami doner.","Ham hock bresaola andouille t-bone, meatball cupim tenderloin spare ribs picanha jowl.  Pork ham meatloaf short ribs landjaeger brisket turducken strip steak andouille frankfurter pork chop pork belly.  Doner tenderloin chicken chuck ham.  Swine picanha biltong ham doner salami shankle prosciutto landjaeger porchetta.","Swine landjaeger meatloaf spare ribs sausage.  Porchetta cow ham hock ham, pork belly shank pork chop pork kielbasa ribeye pig cupim tongue.  Short ribs ground round porchetta turkey ham hock, salami landjaeger leberkas burgdoggen.  Pork belly burgdoggen shank leberkas.  Flank shank filet mignon, capicola ball tip meatloaf pork belly kielbasa burgdoggen.  Picanha tongue jowl landjaeger, boudin short loin andouille corned beef.  Pork belly fatback pork chop short ribs rump pancetta landjaeger jerky meatloaf cow strip steak sausage.'
        ),
        array(
            'post_title' => 'Tenderloin short ribs cow ground round, drumstick\'s kielbasa burgdoggen doner chicken',
            'post_excerpt' => 'Kielbasa jowl, ham hock beef ribs kevin prosciutto t-bone porchetta tail sausage.  Tri-tip sirloin frankfurter kielbasa, jerky spare ribs leberkas ham tenderloin.',
            'post_content' => 'Biltong strip steak shoulder, salami brisket turducken spare ribs.  T-bone meatball pork venison.  Prosciutto jowl andouille tri-tip brisket, pork salami tail burgdoggen pork chop ground round drumstick sausage pastrami beef ribs.  Rump pancetta chicken corned beef kevin.  Pork belly sirloin pork loin frankfurter leberkas.","Short loin ribeye cupim turducken, filet mignon sirloin picanha chuck kevin brisket.  Sirloin meatball corned beef kielbasa hamburger.  Shoulder ground round kevin, pork loin short ribs ham hock pancetta.  Ham hock cow kielbasa pork loin pig doner chuck pastrami.","Tenderloin pancetta leberkas short loin sirloin burgdoggen meatball frankfurter.  Capicola ball tip bresaola kielbasa jowl, ham hock beef ribs kevin prosciutto t-bone porchetta tail sausage.  Tri-tip sirloin frankfurter kielbasa, jerky spare ribs leberkas ham tenderloin.  Kevin hamburger boudin meatloaf flank, shoulder ball tip t-bone rump ribeye ham hock turkey shank.  Ribeye shoulder meatloaf kevin pancetta fatback flank filet mignon short ribs.","Sausage shankle flank boudin.  Flank biltong meatloaf jerky pork swine shankle tenderloin sirloin chicken shank.  Tenderloin short ribs cow ground round, drumstick kielbasa burgdoggen doner chicken t-bone turkey.  Ham hock frankfurter pork loin tongue porchetta ribeye tenderloin jowl fatback beef ribs tri-tip.  Pastrami meatball shankle pig drumstick.  Hamburger pancetta spare ribs tri-tip shankle pork tongue bresaola.","Boudin cupim rump, filet mignon turkey doner sausage tenderloin.  Strip steak swine meatball, prosciutto pig jerky flank.  Ribeye bacon boudin ham hock, turducken salami frankfurter pork loin pork chop jowl.  T-bone prosciutto burgdoggen short loin meatloaf beef chuck.'
        ),
        array(
            'post_title' => 'Ball tip, "pastrami sirloin" drumstick flank...',
            'post_excerpt' => 'Kevin meatball hamburger, cupim shank tenderloin frankfurter.  Landjaeger jowl venison kielbasa, bresaola tenderloin cupim brisket.  Boudin chuck corned beef jowl meatball.',
            'post_content' => 'Fatback capicola sirloin short loin.  Frankfurter pork chop shoulder chicken bresaola turkey.  Tongue sirloin flank, pancetta prosciutto landjaeger bresaola biltong shoulder ribeye short ribs sausage tri-tip brisket drumstick.  Spare ribs porchetta rump pastrami.","Turkey cupim bresaola ham hock biltong filet mignon picanha pork belly cow meatball.  Kevin fatback alcatra short loin flank short ribs doner meatloaf chuck bacon burgdoggen.  Chuck turkey turducken, beef ribs landjaeger biltong porchetta andouille brisket meatball short loin alcatra ham flank picanha.  Ball tip porchetta meatball sausage.  Swine porchetta fatback brisket.","Meatball picanha venison, brisket kielbasa prosciutto ball tip bresaola short ribs short loin porchetta ham hock filet mignon swine.  Prosciutto brisket fatback salami pork belly shankle jerky beef ribs.  Kevin meatball hamburger, cupim shank tenderloin frankfurter.  Landjaeger jowl venison kielbasa, bresaola tenderloin cupim brisket.  Boudin chuck corned beef jowl meatball.","Pork sirloin turkey chicken pancetta, ribeye pork belly tenderloin t-bone.  Tongue tenderloin picanha pastrami leberkas pork chop drumstick.  Pork chop turkey beef ribs shankle chicken shank meatball.  Sausage beef drumstick cow venison pork kielbasa cupim pig ribeye.  Landjaeger capicola ball tip, pastrami sirloin drumstick flank.","Flank chicken doner jowl.  Landjaeger doner pork chop venison.  Tail shank capicola pork belly venison, chicken kevin pork loin beef bresaola.  Pork burgdoggen frankfurter bacon drumstick rump cupim chicken.  Tenderloin pancetta doner meatball andouille burgdoggen turkey pork loin sirloin.  Chicken turkey burgdoggen venison.  Swine shoulder meatball short loin, pork jowl short ribs.'
        ),
        array(
            'post_title' => 'Chop short loin sausage tri-tip ribeye short ribs spare ribs meatloaf',
            'post_excerpt' => 'Shankle andouille picanha t-bone ground round chicken pastrami chuck.  Chicken alcatra pastrami tongue fatback brisket doner spare ribs porchetta capicola venison biltong flank sausage hamburger.',
            'post_content' => 'Beef ribs short loin shank pancetta, strip steak capicola cow beef pork rump spare ribs.  Pork chop frankfurter kevin pork loin meatball short loin filet mignon short ribs meatloaf kielbasa jowl sausage tail.  Frankfurter pastrami ball tip pancetta, swine short ribs hamburger ground round prosciutto turkey venison pig bacon jowl.  Meatloaf bacon cow, kielbasa pork loin beef ribs picanha ball tip tenderloin venison porchetta biltong.  Swine tongue landjaeger drumstick cupim, tri-tip pork chop.  Turkey chicken ham hock landjaeger t-bone, spare ribs kevin.","Shankle andouille picanha t-bone ground round chicken pastrami chuck.  Chicken alcatra pastrami tongue fatback brisket doner spare ribs porchetta capicola venison biltong flank sausage hamburger.  Doner kielbasa sausage frankfurter jerky, cupim pig salami alcatra shoulder.  Meatloaf cow doner chuck salami kielbasa filet mignon sirloin short ribs ball tip rump bacon.  Pork chop ball tip jerky andouille salami tongue boudin rump shank jowl prosciutto strip steak.","Andouille pancetta short ribs ham short loin beef meatloaf picanha jowl filet mignon brisket kevin kielbasa biltong.  Jerky leberkas porchetta hamburger, prosciutto beef cupim sausage ground round venison andouille biltong.  Rump biltong corned beef brisket.  Doner sausage picanha, chicken corned beef kevin cupim ground round.  Corned beef porchetta pancetta tongue picanha.  Porchetta pancetta corned beef chicken leberkas kielbasa andouille.","Sausage hamburger shankle short ribs tenderloin ham hock.  Pork chop shank hamburger cupim turducken bresaola.  Pork beef boudin, pork chop short loin sausage tri-tip ribeye short ribs spare ribs meatloaf.  Jerky hamburger turducken, tri-tip andouille tongue shoulder pork chop venison.","Burgdoggen jerky bacon beef, hamburger doner pork belly.  Andouille beef ribs porchetta, pastrami meatball bresaola jowl ham hock.  Bacon tail andouille ball tip bresaola pork loin pancetta venison turducken corned beef.  Andouille brisket pastrami landjaeger beef hamburger, fatback chicken swine turkey cow.  Salami kevin drumstick short loin, beef ribs corned beef tri-tip biltong boudin venison spare ribs t-bone cupim.  Drumstick ham shank ball tip.  Swine pork chop capicola strip steak, short ribs burgdoggen ham hock turkey sirloin.'
        ),
        array(
            'post_title' => 'Meatloaf turducken andouille jerky spare ribs filet mignon cow pork loin pastrami',
            'post_excerpt' => 'Shoulder salami ribeye shankle.  Jerky strip steak ham, cupim tail cow ball tip pig t-bone venison. Swine hamburger capicola, alcatra ribeye ham pancetta.  Meatloaf turducken andouille jerky spare ribs filet mignon cow pork loin pastrami beef tri-tip venison burgdoggen meatball.',
            'post_content' => 'Kielbasa swine ground round drumstick brisket filet mignon tenderloin alcatra.  Shankle capicola biltong filet mignon, short loin ribeye tail sausage turducken spare ribs pork chop ham hock rump short ribs drumstick.  Meatball boudin meatloaf andouille t-bone.  Shank beef salami prosciutto jerky jowl bresaola ham drumstick hamburger beef ribs shoulder.","Pastrami pork belly bacon pancetta hamburger shoulder.  Fatback shoulder salami flank, sirloin t-bone chuck ham hock drumstick bresaola sausage pancetta pork.  Jowl chuck flank ground round.  Shankle shank leberkas venison.","Shank spare ribs biltong shoulder, tenderloin venison landjaeger.  Flank venison fatback, tongue short loin tenderloin alcatra ground round.  Pork loin short loin pig tenderloin leberkas beef ribs tri-tip sirloin drumstick landjaeger.  Bresaola rump pork belly strip steak pancetta.  Shoulder salami ribeye shankle.  Jerky strip steak ham, cupim tail cow ball tip pig t-bone venison.","Swine hamburger capicola, alcatra ribeye ham pancetta.  Meatloaf turducken andouille jerky spare ribs filet mignon cow pork loin pastrami beef tri-tip venison burgdoggen meatball.  Biltong pastrami venison porchetta pork loin chuck.  Salami ball tip bresaola capicola leberkas, turducken chuck pastrami.  Filet mignon shoulder fatback short loin capicola drumstick bresaola.  Strip steak spare ribs burgdoggen salami cow, doner leberkas jerky corned beef alcatra.  Swine meatloaf turducken venison picanha pork chop turkey rump corned beef capicola strip steak drumstick biltong ground round shankle.","Tongue turkey short ribs jerky chuck shoulder turducken beef kevin.  Flank chuck capicola pork belly cupim.  Short loin meatloaf beef alcatra, jerky venison hamburger kielbasa kevin brisket frankfurter ground round.  Capicola burgdoggen spare ribs, shank tri-tip meatloaf porchetta chuck.'
        )
    );

    // Get rand content
    $rand_key = array_rand( $array, 1 );
    $return = ( isset($array[$rand_key][$key]) ) ? sanitize_text_field( $array[$rand_key][$key] ) : '' ;

    return $return;
}